"""Initial migration

Revision ID: 420e6b06c2f0
Revises: 
Create Date: 2025-11-20 09:36:10.446680

"""
from alembic import op
import sqlalchemy as sa


revision = '420e6b06c2f0'
down_revision = None
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skills',
    sa.Column('skill_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('platform', sa.String(length=100), nullable=True),
    sa.Column('segment', sa.String(length=100), nullable=True),
    sa.Column('product_portfolio', sa.String(length=100), nullable=True),
    sa.Column('speciality_area', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('skill_id'),
    schema='FSQ87086'
    )
    op.create_index(op.f('ix_FSQ87086_skills_skill_id'), 'skills', ['skill_id'], unique=False, schema='FSQ87086')
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_type', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    schema='FSQ87086'
    )
    op.create_index(op.f('ix_FSQ87086_users_email'), 'users', ['email'], unique=True, schema='FSQ87086')
    op.create_index(op.f('ix_FSQ87086_users_user_id'), 'users', ['user_id'], unique=False, schema='FSQ87086')
    op.create_table('assets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('asset_name', sa.String(length=255), nullable=True),
    sa.Column('asset_desc', sa.Text(), nullable=True),
    sa.Column('used_in_project', sa.String(length=255), nullable=True),
    sa.Column('ai_adoption', sa.String(length=100), nullable=True),
    sa.Column('your_contribution', sa.Text(), nullable=True),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('url', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['manager_id'], ['FSQ87086.users.user_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['FSQ87086.users.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='FSQ87086'
    )
    op.create_index(op.f('ix_FSQ87086_assets_id'), 'assets', ['id'], unique=False, schema='FSQ87086')
    op.create_table('projects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('project_name', sa.String(length=255), nullable=True),
    sa.Column('client_name', sa.String(length=255), nullable=True),
    sa.Column('tech_used', sa.Text(), nullable=True),
    sa.Column('your_role', sa.String(length=255), nullable=True),
    sa.Column('project_desc', sa.Text(), nullable=True),
    sa.Column('is_foak', sa.Boolean(), nullable=True),
    sa.Column('asset_used', sa.String(length=255), nullable=True),
    sa.Column('asset_name', sa.String(length=255), nullable=True),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['manager_id'], ['FSQ87086.users.user_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['FSQ87086.users.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='FSQ87086'
    )
    op.create_index(op.f('ix_FSQ87086_projects_id'), 'projects', ['id'], unique=False, schema='FSQ87086')
    op.create_table('request',
    sa.Column('request_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('submission_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('data', sa.TEXT(), nullable=True),
    sa.Column('section_type', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['manager_id'], ['FSQ87086.users.user_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['FSQ87086.users.user_id'], ),
    sa.PrimaryKeyConstraint('request_id'),
    schema='FSQ87086'
    )
    op.create_index(op.f('ix_FSQ87086_request_request_id'), 'request', ['request_id'], unique=False, schema='FSQ87086')
    op.create_table('user_cert',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('cert_type', sa.String(length=100), nullable=True),
    sa.Column('cert_name', sa.String(length=255), nullable=True),
    sa.Column('cert_file_path', sa.String(length=512), nullable=True),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('cert_cat', sa.String(length=100), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['manager_id'], ['FSQ87086.users.user_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['FSQ87086.users.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='FSQ87086'
    )
    op.create_index(op.f('ix_FSQ87086_user_cert_id'), 'user_cert', ['id'], unique=False, schema='FSQ87086')
    op.create_table('user_skills',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('proficiency_level', sa.String(length=50), nullable=True),
    sa.Column('platform', sa.String(length=100), nullable=True),
    sa.Column('segment', sa.String(length=100), nullable=True),
    sa.Column('product_portfolio', sa.String(length=100), nullable=True),
    sa.Column('speciality_area', sa.String(length=100), nullable=True),
    sa.Column('product_line', sa.String(length=100), nullable=True),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('skill_type', sa.String(length=50), nullable=True),
    sa.Column('yoe', sa.String(length=50), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['manager_id'], ['FSQ87086.users.user_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['FSQ87086.users.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='FSQ87086'
    )
    op.create_index(op.f('ix_FSQ87086_user_skills_id'), 'user_skills', ['id'], unique=False, schema='FSQ87086')
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_FSQ87086_user_skills_id'), table_name='user_skills', schema='FSQ87086')
    op.drop_table('user_skills', schema='FSQ87086')
    op.drop_index(op.f('ix_FSQ87086_user_cert_id'), table_name='user_cert', schema='FSQ87086')
    op.drop_table('user_cert', schema='FSQ87086')
    op.drop_index(op.f('ix_FSQ87086_request_request_id'), table_name='request', schema='FSQ87086')
    op.drop_table('request', schema='FSQ87086')
    op.drop_index(op.f('ix_FSQ87086_projects_id'), table_name='projects', schema='FSQ87086')
    op.drop_table('projects', schema='FSQ87086')
    op.drop_index(op.f('ix_FSQ87086_assets_id'), table_name='assets', schema='FSQ87086')
    op.drop_table('assets', schema='FSQ87086')
    op.drop_index(op.f('ix_FSQ87086_users_user_id'), table_name='users', schema='FSQ87086')
    op.drop_index(op.f('ix_FSQ87086_users_email'), table_name='users', schema='FSQ87086')
    op.drop_table('users', schema='FSQ87086')
    op.drop_index(op.f('ix_FSQ87086_skills_skill_id'), table_name='skills', schema='FSQ87086')
    op.drop_table('skills', schema='FSQ87086')
    # ### end Alembic commands ###
